version: "3.8"

services:
  mqtt_alerter:
    build: .
    image: weewx-mqtt-alerter:latest
    container_name: mqtt_alerter
    command: python mqtt_pushover_alert.py
    volumes:
      - settings_data:/app
    restart: unless-stopped

  web_frontend:
    build: .
    image: weewx-mqtt-alerter:latest
    container_name: web_frontend
    command: gunicorn -b 0.0.0.0:8000 settings_web:app --timeout 300 --log-level warning
    ports:
      - "8999:8000"
    volumes:
      - settings_data:/app
    restart: unless-stopped

volumes:
  settings_data: